#!/bin/sh -e

[ "$1" = configure ] || exit 0

oldcatdir=/var/catman
catdir=/var/cache/man
maybesetuid='man mandb'
conffile=/etc/manpath.config

. /usr/share/debconf/confmodule
db_version 2.0
db_get man-db/install-setuid

# Sorry about this, but #98224 is right - statoverrides don't work as
# cleanly as I'd hoped here. I'm going to have to carry around some cruft
# for a while.
for x in $maybesetuid; do
    if dpkg --compare-versions "$2" eq 2.3.18-4 && \
	    [ "`dpkg-statoverride --list /usr/lib/man-db/$x`" = \
	      "man root 4755 /usr/lib/man-db/$x" ]; then
	dpkg-statoverride --remove /usr/lib/man-db/$x
    fi
done

if [ "$RET" = true ]; then
    # man and mandb are to be installed setuid man, and for now we need the
    # wrapper.
    owner=man:root
    mode=4755
    issetuid=1
else
    # man and mandb are not to be installed setuid, and we install symlinks
    # directly to the executables.
    owner=root:root
    mode=0755
    issetuid=0
fi

for x in $maybesetuid; do
    if [ $issetuid -eq 1 ]; then target=wrapper; else target=$x; fi
    # No statoverrides available or none exist for us ...
    if [ ! -x /usr/sbin/dpkg-statoverride ] || \
	    ! dpkg-statoverride --list /usr/lib/man-db/$x >/dev/null; then
	chown $owner /usr/lib/man-db/$x
	chmod $mode  /usr/lib/man-db/$x
	ln -sf ../lib/man-db/$target /usr/bin/$x
    fi
    # Make sure we end up with a symlink
    [ -L /usr/bin/$x ] || ln -sf ../lib/man-db/$target /usr/bin/$x
done

if [ -e /etc/cron.daily/man.moved-by-preinst ]; then
    rm /etc/cron.daily/man.moved-by-preinst
fi
if [ -e /etc/cron.weekly/catman.moved-by-preinst ]; then
    rm /etc/cron.weekly/catman.moved-by-preinst
fi

if dpkg --compare-versions "$2" lt 2.3.18; then
    # /usr/local/man now mapped to /var/cache/man/oldlocal
    if [ -d $catdir/local -a ! -d $catdir/oldlocal ]; then
	mv -f $catdir/local $catdir/oldlocal
    fi
fi

# Old packages removed catpages on upgrade. The preinst hack should have
# avoided this, but let's be sure.
if [ ! -d $catdir ]; then
    install -d -g root -m 02755 -o man $catdir
fi

build_db=0

if [ ! -f $catdir/index.bt ]; then
    # If the build-database question was never asked, this is probably a
    # fresh install, or maybe we're reconfiguring. The default is to build
    # the database if and only if we aren't setuid.
    db_fget man-db/build-database seen
    if [ "$RET" = true ]; then
	if [ $issetuid -eq 0 ]; then
	    build_db=1
	fi
    else
	# This should probably only fire when upgrading from less than
	# 2.3.16, but it doesn't really matter.
	db_get man-db/build-database
	if [ "$RET" = true ]; then
	    build_db=1
	fi
    fi
elif dpkg --compare-versions "$2" lt 2.3.17.1-5; then
    db_get man-db/rebuild-database
    if [ "$RET" = true ]; then
	build_db=1
    fi
fi

if [ $build_db -eq 1 ]; then
    # --pidfile /dev/null so it always starts; mandb isn't really a daemon,
    # but we want to start it like one.
    start-stop-daemon --start --pidfile /dev/null \
		      --startas /usr/lib/man-db/mandb --oknodo --chuid man \
		      --background --nicelevel 10 -- -c >/dev/null 2>/dev/null
fi

#DEBHELPER#

db_stop

exit 0
