#!/bin/sh -e

# Clean up a cron job that the old man package apparently left around.
if [ -e /etc/cron.daily/man ]; then
    echo "  Removing /etc/cron.daily/man cron job from obsolete man package."
    mv /etc/cron.daily/man /etc/cron.daily/man.moved-by-preinst
fi

# Old postrms removed catpages; we don't necessarily want to. Those postrms
# didn't do anything else that's useful now, so remove them.
if [ "$1" = upgrade ] && dpkg --compare-versions "$2" ge 2.3.16; then
    rm -f /var/lib/dpkg/info/man-db.postrm
fi

#DEBHELPER#

exit 0
